
export default [
  { code: "Adlm", number: "166", name: "Adlam",                   impl: { exact: true, }, },
  { code: "Afak", number: "439", name: "",                        impl: null, },
  { code: "Aghb", number: "239", name: "Caucasian_Albanian",      impl: { exact: true, }, },
  { code: "Ahom", number: "338", name: "Ahom",                    impl: { exact: true, }, },
  { code: "Arab", number: "160", name: "Arabic",                  impl: { exact: true, }, },
  { code: "Aran", number: "161", name: "",                        impl: { typographicVariantOf: "Arab", }, },
  { code: "Armi", number: "124", name: "Imperial_Aramaic",        impl: { exact: true, }, },
  { code: "Armn", number: "230", name: "Armenian",                impl: { exact: true, }, },
  { code: "Avst", number: "134", name: "Avestan",                 impl: { exact: true, }, },
  { code: "Bali", number: "360", name: "Balinese",                impl: { exact: true, }, },
  { code: "Bamu", number: "435", name: "Bamum",                   impl: { exact: true, }, },
  { code: "Bass", number: "259", name: "Bassa_Vah",               impl: { exact: true, }, },
  { code: "Batk", number: "365", name: "Batak",                   impl: { exact: true, }, },
  { code: "Beng", number: "325", name: "Bengali",                 impl: { exact: true, }, },
  { code: "Bhks", number: "334", name: "Bhaiksuki",               impl: { exact: true, }, },
  { code: "Blis", number: "550", name: "",                        impl: null, },
  { code: "Bopo", number: "285", name: "Bopomofo",                impl: { exact: true, }, },
  { code: "Brah", number: "300", name: "Brahmi",                  impl: { exact: true, }, },
  { code: "Brai", number: "570", name: "Braille",                 impl: { exact: true, }, },
  { code: "Bugi", number: "367", name: "Buginese",                impl: { exact: true, }, },
  { code: "Buhd", number: "372", name: "Buhid",                   impl: { exact: true, }, },
  { code: "Cakm", number: "349", name: "Chakma",                  impl: { exact: true, }, },
  { code: "Cans", number: "440", name: "Canadian_Aboriginal",     impl: { exact: true, }, },
  { code: "Cari", number: "201", name: "Carian",                  impl: { exact: true, }, },
  { code: "Cham", number: "358", name: "Cham",                    impl: { exact: true, }, },
  { code: "Cher", number: "445", name: "Cherokee",                impl: { exact: true, }, },
  { code: "Chrs", number: "109", name: "Chorasmian",              impl: { exact: true, }, },
  { code: "Cirt", number: "291", name: "",                        impl: null, },
  { code: "Copt", number: "204", name: "Coptic",                  impl: { exact: true, }, },
  { code: "Cpmn", number: "402", name: "",                        impl: null, },
  { code: "Cprt", number: "403", name: "Cypriot",                 impl: { exact: true, }, },
  { code: "Cyrl", number: "220", name: "Cyrillic",                impl: { exact: true, }, },
  { code: "Cyrs", number: "221", name: "",                        impl: { typographicVariantOf: "Cyrl", }, },
  { code: "Deva", number: "315", name: "Devanagari",              impl: { exact: true, }, },
  { code: "Diak", number: "342", name: "Dives_Akuru",             impl: { exact: true, }, },
  { code: "Dogr", number: "328", name: "Dogra",                   impl: { exact: true, }, },
  { code: "Dsrt", number: "250", name: "Deseret",                 impl: { exact: true, }, },
  { code: "Dupl", number: "755", name: "Duployan",                impl: { exact: true, }, },
  { code: "Egyd", number: "070", name: "",                        impl: null, },
  { code: "Egyh", number: "060", name: "",                        impl: null, },
  { code: "Egyp", number: "050", name: "Egyptian_Hieroglyphs",    impl: { exact: true, }, },
  { code: "Elba", number: "226", name: "Elbasan",                 impl: { exact: true, }, },
  { code: "Elym", number: "128", name: "Elymaic",                 impl: { exact: true, }, },
  { code: "Ethi", number: "430", name: "Ethiopic",                impl: { exact: true, }, },
  { code: "Geok", number: "241", name: "Georgian",                impl: { equals: "Geor", }, },
  { code: "Geor", number: "240", name: "Georgian",                impl: { exact: true, }, },
  { code: "Glag", number: "225", name: "Glagolitic",              impl: { exact: true, }, },
  { code: "Gong", number: "312", name: "Gunjala_Gondi",           impl: { exact: true, }, },
  { code: "Gonm", number: "313", name: "Masaram_Gondi",           impl: { exact: true, }, },
  { code: "Goth", number: "206", name: "Gothic",                  impl: { exact: true, }, },
  { code: "Gran", number: "343", name: "Grantha",                 impl: { exact: true, }, },
  { code: "Grek", number: "200", name: "Greek",                   impl: { exact: true, }, },
  { code: "Gujr", number: "320", name: "Gujarati",                impl: { exact: true, }, },
  { code: "Guru", number: "310", name: "Gurmukhi",                impl: { exact: true, }, },
  { code: "Hanb", number: "503", name: "",                        impl: { unionOf: [ "Bopo", "Hani", ], }, },
  { code: "Hang", number: "286", name: "Hangul",                  impl: { exact: true, }, },
  { code: "Hani", number: "500", name: "Han",                     impl: { exact: true, }, },
  { code: "Hano", number: "371", name: "Hanunoo",                 impl: { exact: true, }, },
  { code: "Hans", number: "501", name: "",                        impl: { containedIn: "Hani", }, },
  { code: "Hant", number: "502", name: "",                        impl: { containedIn: "Hani", }, },
  { code: "Hatr", number: "127", name: "Hatran",                  impl: { exact: true, }, },
  { code: "Hebr", number: "125", name: "Hebrew",                  impl: { exact: true, }, },
  { code: "Hira", number: "410", name: "Hiragana",                impl: { exact: true, }, },
  { code: "Hluw", number: "080", name: "Anatolian_Hieroglyphs",   impl: { exact: true, }, },
  { code: "Hmng", number: "450", name: "Pahawh_Hmong",            impl: { exact: true, }, },
  { code: "Hmnp", number: "451", name: "Nyiakeng_Puachue_Hmong",  impl: { exact: true, }, },
  { code: "Hrkt", number: "412", name: "Katakana_Or_Hiragana",    impl: { unionOf: [ "Hira", "Kana", ], }, },
  { code: "Hung", number: "176", name: "Old_Hungarian",           impl: { exact: true, }, },
  { code: "Inds", number: "610", name: "",                        impl: null, },
  { code: "Ital", number: "210", name: "Old_Italic",              impl: { exact: true, }, },
  { code: "Jamo", number: "284", name: "",                        impl: { containedIn: "Hang", }, },
  { code: "Java", number: "361", name: "Javanese",                impl: { exact: true, }, },
  { code: "Jpan", number: "413", name: "",                        impl: { unionOf: [ "Hani", "Hira", "Kana", ], }, },
  { code: "Jurc", number: "510", name: "",                        impl: null, },
  { code: "Kali", number: "357", name: "Kayah_Li",                impl: { exact: true, }, },
  { code: "Kana", number: "411", name: "Katakana",                impl: { exact: true, }, },
  { code: "Khar", number: "305", name: "Kharoshthi",              impl: { exact: true, }, },
  { code: "Khmr", number: "355", name: "Khmer",                   impl: { exact: true, }, },
  { code: "Khoj", number: "322", name: "Khojki",                  impl: { exact: true, }, },
  { code: "Kitl", number: "505", name: "",                        impl: null, },
  { code: "Kits", number: "288", name: "Khitan_Small_Script",     impl: { exact: true, }, },
  { code: "Knda", number: "345", name: "Kannada",                 impl: { exact: true, }, },
  { code: "Kore", number: "287", name: "",                        impl: { unionOf: [ "Hang", "Hani", ], }, },
  { code: "Kpel", number: "436", name: "",                        impl: null, },
  { code: "Kthi", number: "317", name: "Kaithi",                  impl: { exact: true, }, },
  { code: "Lana", number: "351", name: "Tai_Tham",                impl: { exact: true, }, },
  { code: "Laoo", number: "356", name: "Lao",                     impl: { exact: true, }, },
  { code: "Latf", number: "217", name: "",                        impl: { typographicVariantOf: "Latn", }, },
  { code: "Latg", number: "216", name: "",                        impl: { typographicVariantOf: "Latn", }, },
  { code: "Latn", number: "215", name: "Latin",                   impl: { exact: true, }, },
  { code: "Leke", number: "364", name: "",                        impl: null, },
  { code: "Lepc", number: "335", name: "Lepcha",                  impl: { exact: true, }, },
  { code: "Limb", number: "336", name: "Limbu",                   impl: { exact: true, }, },
  { code: "Lina", number: "400", name: "Linear_A",                impl: { exact: true, }, },
  { code: "Linb", number: "401", name: "Linear_B",                impl: { exact: true, }, },
  { code: "Lisu", number: "399", name: "Lisu",                    impl: { exact: true, }, },
  { code: "Loma", number: "437", name: "",                        impl: null, },
  { code: "Lyci", number: "202", name: "Lycian",                  impl: { exact: true, }, },
  { code: "Lydi", number: "116", name: "Lydian",                  impl: { exact: true, }, },
  { code: "Mahj", number: "314", name: "Mahajani",                impl: { exact: true, }, },
  { code: "Maka", number: "366", name: "Makasar",                 impl: { exact: true, }, },
  { code: "Mand", number: "140", name: "Mandaic",                 impl: { exact: true, }, },
  { code: "Mani", number: "139", name: "Manichaean",              impl: { exact: true, }, },
  { code: "Marc", number: "332", name: "Marchen",                 impl: { exact: true, }, },
  { code: "Maya", number: "090", name: "",                        impl: null, },
  { code: "Medf", number: "265", name: "Medefaidrin",             impl: { exact: true, }, },
  { code: "Mend", number: "438", name: "Mende_Kikakui",           impl: { exact: true, }, },
  { code: "Merc", number: "101", name: "Meroitic_Cursive",        impl: { exact: true, }, },
  { code: "Mero", number: "100", name: "Meroitic_Hieroglyphs",    impl: { exact: true, }, },
  { code: "Mlym", number: "347", name: "Malayalam",               impl: { exact: true, }, },
  { code: "Modi", number: "324", name: "Modi",                    impl: { exact: true, }, },
  { code: "Mong", number: "145", name: "Mongolian",               impl: { exact: true, }, },
  { code: "Moon", number: "218", name: "",                        impl: null, },
  { code: "Mroo", number: "264", name: "Mro",                     impl: { exact: true, }, },
  { code: "Mtei", number: "337", name: "Meetei_Mayek",            impl: { exact: true, }, },
  { code: "Mult", number: "323", name: "Multani",                 impl: { exact: true, }, },
  { code: "Mymr", number: "350", name: "Myanmar",                 impl: { exact: true, }, },
  { code: "Nand", number: "311", name: "Nandinagari",             impl: { exact: true, }, },
  { code: "Narb", number: "106", name: "Old_North_Arabian",       impl: { exact: true, }, },
  { code: "Nbat", number: "159", name: "Nabataean",               impl: { exact: true, }, },
  { code: "Newa", number: "333", name: "Newa",                    impl: { exact: true, }, },
  { code: "Nkdb", number: "085", name: "",                        impl: null, },
  { code: "Nkgb", number: "420", name: "",                        impl: null, },
  { code: "Nkoo", number: "165", name: "Nko",                     impl: { exact: true, }, },
  { code: "Nshu", number: "499", name: "Nushu",                   impl: { exact: true, }, },
  { code: "Ogam", number: "212", name: "Ogham",                   impl: { exact: true, }, },
  { code: "Olck", number: "261", name: "Ol_Chiki",                impl: { exact: true, }, },
  { code: "Orkh", number: "175", name: "Old_Turkic",              impl: { exact: true, }, },
  { code: "Orya", number: "327", name: "Oriya",                   impl: { exact: true, }, },
  { code: "Osge", number: "219", name: "Osage",                   impl: { exact: true, }, },
  { code: "Osma", number: "260", name: "Osmanya",                 impl: { exact: true, }, },
  { code: "Ougr", number: "143", name: "",                        impl: null, },
  { code: "Palm", number: "126", name: "Palmyrene",               impl: { exact: true, }, },
  { code: "Pauc", number: "263", name: "Pau_Cin_Hau",             impl: { exact: true, }, },
  { code: "Pcun", number: "015", name: "",                        impl: null, },
  { code: "Pelm", number: "016", name: "",                        impl: null, },
  { code: "Perm", number: "227", name: "Old_Permic",              impl: { exact: true, }, },
  { code: "Phag", number: "331", name: "Phags_Pa",                impl: { exact: true, }, },
  { code: "Phli", number: "131", name: "Inscriptional_Pahlavi",   impl: { exact: true, }, },
  { code: "Phlp", number: "132", name: "Psalter_Pahlavi",         impl: { exact: true, }, },
  { code: "Phlv", number: "133", name: "",                        impl: null, },
  { code: "Phnx", number: "115", name: "Phoenician",              impl: { exact: true, }, },
  { code: "Plrd", number: "282", name: "Miao",                    impl: { exact: true, }, },
  { code: "Piqd", number: "293", name: "",                        impl: null, },
  { code: "Prti", number: "130", name: "Inscriptional_Parthian",  impl: { exact: true, }, },
  { code: "Psin", number: "103", name: "",                        impl: null, },
  { code: "Qaaa", number: "900", name: "",                        impl: null, },
  { code: "Qaab", number: "901", name: "",                        impl: null, },
  { code: "Qaac", number: "902", name: "",                        impl: null, },
  { code: "Qaad", number: "903", name: "",                        impl: null, },
  { code: "Qaae", number: "904", name: "",                        impl: null, },
  { code: "Qaaf", number: "905", name: "",                        impl: null, },
  { code: "Qaag", number: "906", name: "",                        impl: null, },
  { code: "Qaah", number: "907", name: "",                        impl: null, },
  { code: "Qaai", number: "908", name: "",                        impl: null, },
  { code: "Qaaj", number: "909", name: "",                        impl: null, },
  { code: "Qaak", number: "910", name: "",                        impl: null, },
  { code: "Qaal", number: "911", name: "",                        impl: null, },
  { code: "Qaam", number: "912", name: "",                        impl: null, },
  { code: "Qaan", number: "913", name: "",                        impl: null, },
  { code: "Qaao", number: "914", name: "",                        impl: null, },
  { code: "Qaap", number: "915", name: "",                        impl: null, },
  { code: "Qaaq", number: "916", name: "",                        impl: null, },
  { code: "Qaar", number: "917", name: "",                        impl: null, },
  { code: "Qaas", number: "918", name: "",                        impl: null, },
  { code: "Qaat", number: "919", name: "",                        impl: null, },
  { code: "Qaau", number: "920", name: "",                        impl: null, },
  { code: "Qaav", number: "921", name: "",                        impl: null, },
  { code: "Qaaw", number: "922", name: "",                        impl: null, },
  { code: "Qaax", number: "923", name: "",                        impl: null, },
  { code: "Qaay", number: "924", name: "",                        impl: null, },
  { code: "Qaaz", number: "925", name: "",                        impl: null, },
  { code: "Qaba", number: "926", name: "",                        impl: null, },
  { code: "Qabb", number: "927", name: "",                        impl: null, },
  { code: "Qabc", number: "928", name: "",                        impl: null, },
  { code: "Qabd", number: "929", name: "",                        impl: null, },
  { code: "Qabe", number: "930", name: "",                        impl: null, },
  { code: "Qabf", number: "931", name: "",                        impl: null, },
  { code: "Qabg", number: "932", name: "",                        impl: null, },
  { code: "Qabh", number: "933", name: "",                        impl: null, },
  { code: "Qabi", number: "934", name: "",                        impl: null, },
  { code: "Qabj", number: "935", name: "",                        impl: null, },
  { code: "Qabk", number: "936", name: "",                        impl: null, },
  { code: "Qabl", number: "937", name: "",                        impl: null, },
  { code: "Qabm", number: "938", name: "",                        impl: null, },
  { code: "Qabn", number: "939", name: "",                        impl: null, },
  { code: "Qabo", number: "940", name: "",                        impl: null, },
  { code: "Qabp", number: "941", name: "",                        impl: null, },
  { code: "Qabq", number: "942", name: "",                        impl: null, },
  { code: "Qabr", number: "943", name: "",                        impl: null, },
  { code: "Qabs", number: "944", name: "",                        impl: null, },
  { code: "Qabt", number: "945", name: "",                        impl: null, },
  { code: "Qabu", number: "946", name: "",                        impl: null, },
  { code: "Qabv", number: "947", name: "",                        impl: null, },
  { code: "Qabw", number: "948", name: "",                        impl: null, },
  { code: "Qabx", number: "949", name: "",                        impl: null, },
  { code: "Ranj", number: "303", name: "",                        impl: null, },
  { code: "Rjng", number: "363", name: "Rejang",                  impl: { exact: true, }, },
  { code: "Rohg", number: "167", name: "Hanifi_Rohingya",         impl: { exact: true, }, },
  { code: "Roro", number: "620", name: "",                        impl: null, },
  { code: "Runr", number: "211", name: "Runic",                   impl: { exact: true, }, },
  { code: "Samr", number: "123", name: "Samaritan",               impl: { exact: true, }, },
  { code: "Sara", number: "292", name: "",                        impl: null, },
  { code: "Sarb", number: "105", name: "Old_South_Arabian",       impl: { exact: true, }, },
  { code: "Saur", number: "344", name: "Saurashtra",              impl: { exact: true, }, },
  { code: "Sgnw", number: "095", name: "SignWriting",             impl: { exact: true, }, },
  { code: "Shaw", number: "281", name: "Shavian",                 impl: { exact: true, }, },
  { code: "Shrd", number: "319", name: "Sharada",                 impl: { exact: true, }, },
  { code: "Shui", number: "530", name: "",                        impl: null, },
  { code: "Sidd", number: "302", name: "Siddham",                 impl: { exact: true, }, },
  { code: "Sind", number: "318", name: "Khudawadi",               impl: { exact: true, }, },
  { code: "Sinh", number: "348", name: "Sinhala",                 impl: { exact: true, }, },
  { code: "Sogd", number: "141", name: "Sogdian",                 impl: { exact: true, }, },
  { code: "Sogo", number: "142", name: "Old_Sogdian",             impl: { exact: true, }, },
  { code: "Sora", number: "398", name: "Sora_Sompeng",            impl: { exact: true, }, },
  { code: "Soyo", number: "329", name: "Soyombo",                 impl: { exact: true, }, },
  { code: "Sund", number: "362", name: "Sundanese",               impl: { exact: true, }, },
  { code: "Sylo", number: "316", name: "Syloti_Nagri",            impl: { exact: true, }, },
  { code: "Syrc", number: "135", name: "Syriac",                  impl: { exact: true, }, },
  { code: "Syre", number: "138", name: "",                        impl: { typographicVariantOf: "Syrc", }, },
  { code: "Syrj", number: "137", name: "",                        impl: { typographicVariantOf: "Syrc", }, },
  { code: "Syrn", number: "136", name: "",                        impl: { typographicVariantOf: "Syrc", }, },
  { code: "Tagb", number: "373", name: "Tagbanwa",                impl: { exact: true, }, },
  { code: "Takr", number: "321", name: "Takri",                   impl: { exact: true, }, },
  { code: "Tale", number: "353", name: "Tai_Le",                  impl: { exact: true, }, },
  { code: "Talu", number: "354", name: "New_Tai_Lue",             impl: { exact: true, }, },
  { code: "Taml", number: "346", name: "Tamil",                   impl: { exact: true, }, },
  { code: "Tang", number: "520", name: "Tangut",                  impl: { exact: true, }, },
  { code: "Tavt", number: "359", name: "Tai_Viet",                impl: { exact: true, }, },
  { code: "Telu", number: "340", name: "Telugu",                  impl: { exact: true, }, },
  { code: "Teng", number: "290", name: "",                        impl: null, },
  { code: "Tfng", number: "120", name: "Tifinagh",                impl: { exact: true, }, },
  { code: "Tglg", number: "370", name: "Tagalog",                 impl: { exact: true, }, },
  { code: "Thaa", number: "170", name: "Thaana",                  impl: { exact: true, }, },
  { code: "Thai", number: "352", name: "Thai",                    impl: { exact: true, }, },
  { code: "Tibt", number: "330", name: "Tibetan",                 impl: { exact: true, }, },
  { code: "Tirh", number: "326", name: "Tirhuta",                 impl: { exact: true, }, },
  { code: "Tnsa", number: "275", name: "",                        impl: null, },
  { code: "Toto", number: "294", name: "",                        impl: null, },
  { code: "Ugar", number: "040", name: "Ugaritic",                impl: { exact: true, }, },
  { code: "Vaii", number: "470", name: "Vai",                     impl: { exact: true, }, },
  { code: "Visp", number: "280", name: "",                        impl: null, },
  { code: "Vith", number: "228", name: "",                        impl: null, },
  { code: "Wara", number: "262", name: "Warang_Citi",             impl: { exact: true, }, },
  { code: "Wcho", number: "283", name: "Wancho",                  impl: { exact: true, }, },
  { code: "Wole", number: "480", name: "",                        impl: null, },
  { code: "Xpeo", number: "030", name: "Old_Persian",             impl: { exact: true, }, },
  { code: "Xsux", number: "020", name: "Cuneiform",               impl: { exact: true, }, },
  { code: "Yezi", number: "192", name: "Yezidi",                  impl: { exact: true, }, },
  { code: "Yiii", number: "460", name: "Yi",                      impl: { exact: true, }, },
  { code: "Zanb", number: "339", name: "Zanabazar_Square",        impl: { exact: true, }, },
  { code: "Zinh", number: "994", name: "Inherited",               impl: { exact: true, }, },
  { code: "Zmth", number: "995", name: "",                        impl: null, },
  { code: "Zsye", number: "993", name: "",                        impl: null, },
  { code: "Zsym", number: "996", name: "",                        impl: null, },
  { code: "Zxxx", number: "997", name: "",                        impl: null, },
  { code: "Zyyy", number: "998", name: "Common",                  impl: { exact: true, }, },
  { code: "Zzzz", number: "999", name: "Unknown",                 impl: { exact: true, }, },
];
